# Generate Random Numbers

`numpy.random` is frequently used for generating random numbers.

For more details, please refer to [Random sampling (numpy.random)](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

In [0]:
import numpy as np

`np.random.seed` sets the seed for the generator.

In [0]:
np.random.seed(1)

`np.random.rand` generates numbers uniformly distribution over $[0, 1)$

In [0]:
np.random.rand(2, 3) # Generate 2 * 3 random numbers

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

`np.radnom.randn` generates numbers following standard normal distribtion.

In [0]:
np.random.randn(2, 3) # Generate 2 * 3 random numbers

array([[-0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ]])

`np.random.randint(low, high)` generates integers ranging from `low` (inclusive) to `high` (exclusive)

In [0]:
np.random.randint(low = 0, high = 4, size = (3, 3))

array([[3, 0, 2],
       [0, 1, 2],
       [2, 0, 3]])

`np.random.choice` geneates random numbers following a given pmf.

In [0]:
a = np.arange(4)
p = [0.1, 0.2, 0.3, 0.4]
np.random.choice(a = a, size=(3, 4), p = p)

array([[2, 2, 3, 3],
       [3, 3, 0, 2],
       [3, 3, 3, 1]])

The sample space is not necessary to be number sets.

In [0]:
a = ['Spade', 'Heart', 'Clud', 'Diamond']
p = [0.25, 0.25, 0.25, 0.25]
np.random.choice(a = a, size=(3, 4), p = p)

array([['Spade', 'Clud', 'Clud', 'Clud'],
       ['Heart', 'Spade', 'Heart', 'Spade'],
       ['Diamond', 'Heart', 'Spade', 'Clud']], dtype='<U7')

It is also possible to draw random samples from other distributions.

Exponential: $f_X(x; \beta) = \frac{1}{\beta}e^{-\frac{x}{\beta}}$, $\beta$ is the scale parameter.

In [0]:
np.random.exponential(scale = 2, size = (2, 3))

array([[2.16136241, 0.70905534, 1.18166682],
       [0.50237771, 0.15238928, 1.26688512]])

Binomial: $P_X(k; n,p) = \binom{n}{k} p^k (1 - p)^{n - k}$.

In [0]:
n = 10
p = 0.8
np.random.binomial(n = n, p = p, size = (3, 3))

array([[10,  6,  9],
       [ 8, 10,  6],
       [ 6,  9,  8]])

More distribution types are shown in the docs. 